Create table hijacking(
    hijacking_id int8 generated by default as identity,
    date_penalty date,
     return_date date,
     vin_number varchar(30),
     primary key (hijacking_id));

insert into hijacking(date_penalty, return_date, vin_number)
values ('1999-05-02','2000-03-03','LIO7894561230'),
       ('2005-08-09',null,'LHU1234567890');

CREATE table type_of_penalty(
    id int8 generated by default as identity,
    type_of_penalty varchar(30),
    fine_amount int4,
    primary key (id));
insert into type_of_penalty(type_of_penalty, fine_amount)
 values ('Проезд на красный свет' , '500'),
        ('превыщение скорости', '1000');
create table violator(
    violator_id int8 generated by default as identity,
    date_of_violator date,
    number_of_the_car varchar(30),
    id int8,
    primary key (violator_id));
insert into violator(date_of_violator, number_of_the_car,id)
VALUES ('2020-05-08','A585ФВ199',1),
       ('2019-01-03','В156АК777',2);