version: "3.9"
services:
  g_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=insurance
      - POSTGRES_USER=Mardali
      - POSTGRES_PASSWORD=Mardali
    volumes:
      - db:/var/lib/postgresql/insurance
    ports:
      - "5438:5432"
volumes:
  db: