create table insurant(
    insurant_id int8 generated by default as identity,
    insurance_number varchar(30),
    number_of_the_car varchar(30),
    insurance_start_date date,
    end_date_of_insurance date,
    primary key (insurant_id));

insert into insurant(insurance_number, number_of_the_car, insurance_start_date, end_date_of_insurance)
values ('')