create table insurance(
    insurance_id int8 generated by default as identity,
    insurance_number varchar(30),
    number_of_the_car varchar(30),
    insurance_start_date date,
    end_date_of_insurance date,
    primary key (insurance_id));

insert into insurance(insurance_number, number_of_the_car, insurance_start_date, end_date_of_insurance)
values ('DLZ5123697','A585ФВ199','2021-08-07','2022-08-06'),
       ('AQW4536568955','В156АК777','2022-02-03','2022-09-22');